openapi: 3.0.1
info:
  title: API_Payment
  description: API Definition of API_Payment
  version: 1.0.0
servers:
- url: http://localhost:8290/payment
paths:
  /:
    get:
      responses:
        default:
          description: Default response
